### PR TITLE
Fix some compilation errors on windows with newest toolkits

### PR DESCRIPTION
**Pull request by syby119**
Change CUDA::nvToolsExt to CUDA::nvtx3 as described in the [issue](https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/530)

Change **operator new** definition from  **unsigned long int** to **size_t** as described in the [issue](https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/530)

### CODE REVIEW

**Comment by mmuetzel** [comment]
I'm looking into this, too.

If I understand correctly, none of these libraries actually depend on NVTX. (Only GraphBLAS_CUDA does. But you didn't touch that.) So, the dependency can probably just be removed completely. But I might be missing or misunderstanding something...

**Comment by syby119** [comment]
> `[Change CUDA::nvToolsExt to CUDA::nvtx3](/DrTimothyAldenDavis/SuiteSparse/pull/542/commits/55005feeba81c55e2ad0c42afa2a2956117f7007) `
> ` [55005fe](/DrTimothyAldenDavis/SuiteSparse/pull/542/commits/55005feeba81c55e2ad0c42afa2a2956117f7007) `
> [ @syby119 ](/syby119)
> ` [Change operator new definition for GPUQREngine](/DrTimothyAldenDavis/SuiteSparse/pull/542/commits/458c87f516a549d9230facca236af759fe9465dd)`

Thank you for your kind reply. Just make the fixes in your commit. I just find its annoying to change the code manually everytime I git pull the repository to compile the code correctly, since dev branch is updating all the time these days. And I'm really eager for the single precision matrix computation functionality.

The **operator new** issue is (here)[https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/533]. I make a duplicate link in the aforehead comment.

**Comment by syby119** [comment]
> I'm looking into this, too.
> 
> If I understand correctly, none of these libraries actually depend on NVTX. (Only GraphBLAS_CUDA does. But you didn't touch that.) So, the dependency can probably just be removed completely. But I might be missing or misunderstanding something...

Thank you for your kind reply. Just make the fixes in your commit. I just find its annoying to change the code manually everytime I git pull the repository to compile the code correctly, since dev branch is updating all the time these days. And I'm really eager for the single precision matrix computation functionality.

The operator new issue is (here)[https://github.com/https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/533]. I make a duplicate link in the aforehead comment.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the update. Does this work with older cmake versions and older CUDA libraries too?

Also -- can you sign the contributor agreement and email me the pdf?  (My organization has a strict requirement about that and I can't do any PRs without it...).

**Comment by syby119** [comment]
> Thanks for the update. Does this work with older cmake versions and older CUDA libraries too?
> 
> Also -- can you sign the contributor agreement and email me the pdf? (My organization has a strict requirement about that and I can't do any PRs without it...).

It should work for the minimum version in the CMakeList.txt. That is the cmake version 3.22 to find the BLAS and Lapack.
Besides, the minimum CUDA version set for the project is CUDA 11.2. So the CUDA::nvtx3 should be valid according to the CMake official documentation. (CUDA::nvtx3 is set in CUDA 10+).

I‘ve send the email with my university mail address and I hope you can receive it.

**Comment by DrTimothyAldenDavis** [comment]
Great!  I was worried that we might need some kind of conditional test based on the cuda version or the cmake version or both.

**Comment by DrTimothyAldenDavis** [comment]
Oops. I merged it into the wrong branch. Should go to dev2. But the two branches are in sync just now so I'll do a PR from dev to dev2 shortly. On my phone just now...

**Pull request merged**
