### PR TITLE
Overhaul build rules with recent lessons learned.

### PR DESCRIPTION
**Pull request by mmuetzel**
Adapt build rules with changes that were needed for CHOLMOD and UMFPACK.

@DrTimothyAldenDavis: I don't know if this will fix the remaining issue with SPEX. But maybe you could give this a try?

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
I'll check it shortly.  Getting close to SuiteSparse 7.4.0.beta1.  Your help has been amazing!

**Comment by mmuetzel** [comment]
Please, wait a couple of minutes before merging.
Found some typos.

**Comment by mmuetzel** [comment]
The typos should be fixed now.

**Comment by DrTimothyAldenDavis** [comment]
Giving it a try now.

I've added methods to all my packages that return the 3 version numbers.  Some of my packages already had these, like cholmod_version.  I haven't posted it yet (I'll merge this in first).

**Pull request merged**
