### PR TITLE
Support None cmake build type

### PR DESCRIPTION
**Pull request by antonio-rojas**
"None" is the default build type in cmake, and used to build packages in Arch Linux.

No pull request can be accepted unless you first sign the Contributor License Agreement [ CONTRIBUTOR-LICENSE.txt ].  Print it as a PDF and email me a signed PDF (digital signature OK).  Submit all PRs to the dev2 branch only.

### CODE REVIEW

**Comment by mmuetzel** [comment]
LGTM.
Thanks!

**Comment by mmuetzel** [comment]
Are there other common build types that should be added to that list?

**Comment by DrTimothyAldenDavis** [comment]
@antonio-rojas : can you email me a signed Contributor Agreement PDF?  Digital signature is fine.

**Comment by mmuetzel** [comment]
Imho, a CLA would be optional for this change. I don't think that it is substantial enough to be copyrightable. (ANAL though.)

**Comment by DrTimothyAldenDavis** [comment]
Yes, it's minor, but I have constraints that I'm not permitted to bypass.

**Comment by antonio-rojas** [comment]
> @antonio-rojas : can you email me a signed Contributor Agreement PDF? Digital signature is fine.

Done

**Comment by antonio-rojas** [comment]
> Are there other common build types that should be added to that list?

Not that I know of

**Comment by DrTimothyAldenDavis** [comment]
I'll add this update to SuiteSparse 7.2.1 -- thanks!

**Pull request merged**
