### PR TITLE
Example: Remove explicit import of transient dependencies.

### PR DESCRIPTION
**Pull request by mmuetzel**
That should no longer be needed. And removing them should allow the CI to check if the CMake Config files are complete.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Looks great -- thanks.

**Comment by DrTimothyAldenDavis** [comment]
I'm seeing errors when building the Example when not using the top level CMakeLists.txt.  After "make local ; make install ; cd Example ; make" I get:

```
CMake Error at /home/davis/dev2/SuiteSparse/lib/cmake/ParU/ParUTargets.cmake:62 (set_target_properties):
  The link interface of target "SuiteSparse::ParU_static" contains:

    OpenMP::OpenMP_CXX

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/davis/dev2/SuiteSparse/lib/cmake/ParU/ParUConfig.cmake:121 (include)
  CMakeLists.txt:104 (find_package)
```

**Comment by mmuetzel** [comment]
Looking into it.

**Comment by mmuetzel** [comment]
PR #662 should fix this issue.

**Pull request merged**
