### PR TITLE
Allow using CMAKE_BUILD_TYPE and CMAKE_${CMAKE_BUILD_TYPE}_POSTFIX to…

### PR DESCRIPTION
**Pull request by opoplawski**
… add a postfix to pkgconfig files

This partially addresses #425 

See also https://discourse.cmake.org/t/how-to-evaluate-config-postfix/8984 for some discussion.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Thanks -- I'm running tests now.  I'm a bit behind (recovering from surgery 2 weeks ago, and I've been away from the keyboard for that whole time; only now slowly getting up to speed).

**Comment by mmuetzel** [comment]
I don't think it is possible to "merge" different `*Target.cmake` files into one. So, I don't think that this change can conceptionally resolve the issue described in #425.
But please let me know if I'm missing something.

**Comment by mmuetzel** [comment]
This is probably superseded by the different approach applied in #468.
Should this PR be closed?

**Comment by DrTimothyAldenDavis** [comment]
Yes, I'll close this now.  Thanks for all the suggestions; it's been very helpful.

**Pull request closed without merging**
