### PR TITLE
GraphBLAS_CUDA: Create pkg-config file

### PR DESCRIPTION
**Pull request by mmuetzel**
This PR adds a pkg-config file for the GraphBLAS_CUDA library and lets GraphBLAS depend on it for static linking if necessary.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Please, wait a minute.

Projects depending on GraphBLAS should probably also inherit `-DSUITESPARSE_CUDA` from the targets or the .pc files if needed.

I'll try to include that in this PR.

**Comment by mmuetzel** [comment]
Should be ready now.

**Comment by DrTimothyAldenDavis** [comment]
Merging it into dev, as well.

**Comment by DrTimothyAldenDavis** [comment]
To be precise, I've got a PR to merge dev2 into dev, but I haven't merged it yet based on your comment about the other pending PR #400.  I'll do that as soon as you think it's ready to merge (maybe for a next beta release of SuiteSparse?).

**Pull request merged**
