### PR TITLE
[CCOLAMD] fix set but unused variable `Int cs`

### LINKED ISSUE #38: [CCOLAMD] Variable `cs` set but not used
**Describe the bug**
```
CCOLAMD/Source/ccolamd.c:1563:9: warning: variable ‘cs’ set but not used [-Wunused-but-set-variable]
1563 |     Int cs ;
     |         ^~                                       
```

**To Reproduce**
Steps to reproduce the behavior.

git clone
cd CCOLAMD
make

**Expected behavior**

No warnings

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - compiler: gcc 9.3.0
 - BLAS and LAPACK library, if applicable N/A
 - CCOLAMD Version: latest from master

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by acxz**
Resolves #38

### CODE REVIEW

**Comment by acxz** [comment]
@DrTimothyAldenDavis do you mind taking a look at this?

**Comment by DrTimothyAldenDavis** [comment]
Yes, but it's later in my queue.   Tight deadlines for other critical work
at the moment.

**Comment by DrTimothyAldenDavis** [comment]
Also need the signed contributor agreement

**Comment by acxz** [comment]
Thx for responding!

No worries.

Didn't realize there was a CLA, mb. I would recommend looking at [cla-bot](https://github.com/apps/cla-bot) or [cla-assisstant](https://github.com/cla-assistant/cla-assistant) to automate this process.

Would this work as a submission of the signed agreement based on:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/CONTRIBUTOR-LICENSE.txt#L29 ? 

> The GitHub user, X<ins> acxz  </ins>, has read and understood the Contributor License Agreement located at https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/CONTRIBUTOR-LICENSE.txt

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the heads up.  I'll check out the cla-bot or cla-assistant.

**Comment by DrTimothyAldenDavis** [comment]
The variable is used when debugging is enable.  Deleting it breaks the code in that case.

**Pull request closed without merging**
