### PR TITLE
LAGraph: First pass for CMake build rules

### PR DESCRIPTION
**Pull request by mmuetzel**
LAGraph still doesn't build with MSVC with these changes. But it gets a couple of steps further. It currently fails to link with the following error:
```
  LINK: command "C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\HostX64\x64\link.exe /nologo experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_AllKCore.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_AllKTruss.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_basic.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_basic_mxv.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_basic_pushpull.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_full.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_full1.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_full1a.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_full2.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_full_mxv.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_pure_c.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_BF_pure_c_double.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_FastGraphletTransform.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_HelloWorld.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_KCore.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_KCoreDecompose.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_KTruss.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_MaximalIndependentSet.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_SquareClustering.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_VertexCentrality_Triangle.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_cc_lacc.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_cdlp.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_dnn.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_lcc.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_msf.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LAGraph_scc.c.obj experimental\CMakeFiles\lagraphx.dir\Release\algorithm\LG_CC_FastSV5.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_Random.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_Random_Matrix.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SFreeContents.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SFreeSet.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SLoadSet.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SRead.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SSaveSet.c.obj experimental\CMakeFiles\lagraphx.dir\Release\utility\LAGraph_SWrite.c.obj /out:dlls\Release\lagraphx.dll /implib:Release\lagraphx.lib /pdb:dlls\Release\lagraphx.pdb /dll /version:1.0 /machine:x64 /INCREMENTAL:NO /DEF:experimental\CMakeFiles\lagraphx.dir\Release\exports.def -LIBPATH:D:\a\SuiteSparse\SuiteSparse\LAGraph\build Release\lagraph.lib D:\a\SuiteSparse\SuiteSparse\GraphBLAS\build\Release\graphblas.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:dlls\Release\lagraphx.dll.manifest" failed (exit code 1120) with the following output:
     Creating library Release\lagraphx.lib and object Release\lagraphx.exp
  LAGraph_AllKCore.c.obj : error LNK2019: unresolved external symbol LAGraph_plus_one_int32 referenced in function LAGraph_KCore_All
  LAGraph_KCore.c.obj : error LNK2001: unresolved external symbol LAGraph_plus_one_int32
  LAGraph_AllKCore.c.obj : error LNK2019: unresolved external symbol LAGraph_plus_one_int64 referenced in function LAGraph_KCore_All
  LAGraph_KCore.c.obj : error LNK2001: unresolved external symbol LAGraph_plus_one_int64
  LAGraph_AllKTruss.c.obj : error LNK2019: unresolved external symbol LAGraph_plus_one_uint32 referenced in function LAGraph_AllKTruss
  LAGraph_KTruss.c.obj : error LNK2001: unresolved external symbol LAGraph_plus_one_uint32
  LAGraph_MaximalIndependentSet.c.obj : error LNK2019: unresolved external symbol LAGraph_any_one_bool referenced in function LAGraph_MaximalIndependentSet
  LAGraph_VertexCentrality_Triangle.c.obj : error LNK2019: unresolved external symbol LAGraph_plus_second_fp64 referenced in function LAGraph_VertexCentrality_Triangle
  LAGraph_VertexCentrality_Triangle.c.obj : error LNK2019: unresolved external symbol LAGraph_plus_one_fp64 referenced in function LAGraph_VertexCentrality_Triangle
  dlls\Release\lagraphx.dll : fatal error LNK1120: 6 unresolved externals
```
I didn't investigate much. It looks like these symbols are indeed only defined as `extern`. But I don't see where they are actually instantiated.
ISTR, that you replaced a similar construct with get_* and set_* functions in a different library...

Additionally, some tests for LAGraph seem to be failing on 32-bit platforms:
```
  96% tests passed, 2 tests failed out of 56
  
  Total Test time (real) = 152.13 sec
  
  The following tests FAILED:
  	 16 - ctest_Malloc (Failed)
  	 39 - ctest_BF (SEGFAULT)
  Errors while running CTest
  Output from these tests are in: D:/a/SuiteSparse/SuiteSparse/LAGraph/build/Testing/Temporary/LastTest.log
  Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
  make: *** [Makefile:66: test] Error 8
  Error: Process completed with exit code 2.
```

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Thanks!  I'll take a look at those symbols.  Those are supposed to be global values that LAGraph initializes with LAGr_Init (see https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev2/LAGraph/src/utility/LAGr_Init.c ).

**Comment by mmuetzel** [comment]
Thanks for merging. 👍

I'm not sure if I follow the code correctly. But iiuc, `LAGr_Init.c` includes `LG_internal.h` which in turn includes `LAGraph.h`. In `LAGraph.h`, these symbols are marked with `LAGRAPH_PUBLIC` which expands to `extern` (+ `__declspec ( dllexport )` I suppose – which doesn't matter for this I'd guess).
Doesn't that mean that the corresponding compilation unit won't export these symbols (but expects them to be defined in a different compilation unit)?

**Comment by DrTimothyAldenDavis** [comment]
I get confused with the Microsoft declspec keywords.  

Those variables marked as LAGRAPH_PUBLIC are supposed to be defined in LAGr_Iniit, and then declared to be global variables that provided for all of LAGraph and also the user application.

**Comment by DrTimothyAldenDavis** [comment]
The LAGRAPH_PUBLIC keyword is supposed to hide the MSVC declspec, and then it becomes just "extern" for normal ANSI C compilers.  But I might have mangled it...

**Pull request merged**
