### PR TITLE
Clean-up for C++ example

### PR DESCRIPTION
**Pull request by mmuetzel**
Thank you for applying the other changes recently. 👍

This PR cleans up some interdependencies between those PRs.

Splitting the header in the example will probably allow to simplify the changes for #267 slightly.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
looks great -- thanks!

**Comment by DrTimothyAldenDavis** [comment]
I'd like to release a v7.1.0 of SuiteSparse soon, where #267 would appear in a later version (say v7.2.0).  I have a beta prelease of v7.1.0 already posted.  I can include these changes.  Are there others I should add?

**Comment by mmuetzel** [comment]
Thanks for accepting this PR.

Imho, it might be good if the change from here could make it into v7.1.0. With them, the example is in a more "consistent" state imho.

#267 still needs some follow-up changes. Preferably in separate PRs. I agree that it would be better to wait until after the release for those changes.

**Comment by DrTimothyAldenDavis** [comment]
Yes, that's what I thought.  I'll go ahead and include it in v7.1.0.beta2.  Thanks.

**Pull request merged**
