### PR TITLE
CHOLMOD GPU: Fix cast

### PR DESCRIPTION
**Pull request by whuaegeanse**
On windows, MSVC throws compilation error.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Could you please show the exact compiler error message?

**Comment by whuaegeanse** [comment]
> Could you please show the exact compiler error message?

@mmuetzel 
00:193>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(120,63): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(121,63): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(122,66): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(123,66): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(124,64): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(125,61): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(126,69): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(120,63): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(121,63): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(122,66): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(123,66): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(124,64): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(125,61): error C2036: 'void *': unknown size
3>D:\zgh\Libs\suitesparse\SuiteSparse\CHOLMOD\Supernodal\../GPU/t_cholmod_gpu.c(126,69): error C2036: 'void *': unknown size

**Comment by mmuetzel** [comment]
Ah. I wasn't aware that void* arithmetic is a GCC extension.

Your change looks good to me. 👍

**Comment by DrTimothyAldenDavis** [comment]
Yes, doing arithmetic on void * is a gcc extension.  It works find on other compilers like clang.  I try to avoid it since I know it doesn't work in the Microsoft compiler.  But I hadn't tested this code on windows before.

**Comment by DrTimothyAldenDavis** [comment]
gcc complains with this update so I added a cast to the final pointer type (double *).

```
[  8%] Building C object CMakeFiles/CHOLMOD_static.dir/Supernodal/cholmod_l_super_numeric.c.o
In file included from /home/faculty/d/davis/dev2/SuiteSparse/CHOLMOD/Supernodal/cholmod_super_numeric.c:70,
                 from /home/faculty/d/davis/dev2/SuiteSparse/CHOLMOD/Supernodal/cholmod_l_super_numeric.c:13:
/home/faculty/d/davis/dev2/SuiteSparse/CHOLMOD/Supernodal/../GPU/t_cholmod_gpu.c: In function ‘r_cholmod_l_gpu_init’:
/home/faculty/d/davis/dev2/SuiteSparse/CHOLMOD/Supernodal/../GPU/t_cholmod_gpu.c:120:20: warning: assignment to ‘double *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
  120 |     gpu_p->d_Lx[1] = (char*)Common->dev_mempool + Common->devBuffSize;
      |                    ^
```

**Pull request merged**
